# Generated by Django 3.1.6 on 2021-02-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(None, 'Choice one'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=6),
        ),
    ]
