# Generated by Django 3.1.6 on 2021-02-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210219_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
